# Generated by Django 4.2.16 on 2024-10-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("zip_code", models.CharField(max_length=10)),
                ("email_address", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("web", models.URLField()),
            ],
        ),
    ]
