# Generated by Django 4.2.16 on 2024-10-16 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Testapp", "0003_customuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="l_company",
            field=models.ForeignKey(
                default=4,
                on_delete=django.db.models.deletion.CASCADE,
                to="Testapp.company",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
