# Generated by Django 4.2.16 on 2024-10-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Testapp", "0004_location_l_company_delete_customuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="l_company",
        ),
        migrations.AddField(
            model_name="location",
            name="l_com",
            field=models.CharField(default="default_value", max_length=100),
        ),
        migrations.AlterField(
            model_name="location",
            name="l_address",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="location",
            name="l_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="location",
            name="l_phone",
            field=models.CharField(max_length=20),
        ),
    ]
