# Generated by Django 4.2.16 on 2024-10-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Testapp", "0006_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="e_img",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
